### PR TITLE
link to the community website

### PR DESCRIPTION
**Pull request by UrielOfir**

### CODE REVIEW

**Comment by UrielOfir** [comment]
fix #10 

@Rivki7 what do you think?

**Comment by Rivki7** [comment]
Hi @UrielOfir, 
Looks good but I think the text in the yellow button should be 'call to action' like 'join us!'. 
What do you think?

**Comment by UrielOfir** [comment]
@Rivki7 
אפשר להחליף -
לחצו כאן כדי להצטרף

**Comment by Rivki7** [comment]
closes #10

**Pull request merged**
